###
POST http://localhost:8080/api/users/signup HTTP/1.1
Content-Type: application/json

{
    "username":"lulu",
    "email":"lulu@icloud.com",
    "password":""
}

###
POST http://localhost:8080/api/users/login HTTP/1.1
Content-Type: application/json

{
    "username":"lulu",
    "password":""
}

###
POST http://localhost:8080/api/nextwatches HTTP/1.1
Authorization: Bearer 
Content-Type: application/json

{
    "watch_id":"663142f650b4130d190f78fa"
}
###
POST http://localhost:8080/api/nextwatches HTTP/1.1
Authorization: Bearer 
Content-Type: application/json

{
    "watch_id":"663142f650b4130d190f78fe"
}

###
POST http://localhost:8080/api/users/signup HTTP/1.1
Content-Type: application/json

{
    "username":"pixie",
    "email":"pixie@icloud.com",
    "password":""
}

###
POST http://localhost:8080/api/users/login HTTP/1.1
Content-Type: application/json

{
    "username":"pixie",
    "password":"iloveoutside"
}

###
POST http://localhost:8080/api/nextwatches HTTP/1.1
Authorization: Bearer 
Content-Type: application/json

{
    "watch_id":"663142f650b4130d190f78fb"
}
###
POST http://localhost:8080/api/nextwatches HTTP/1.1
Authorization: Bearer 
Content-Type: application/json

{
    "watch_id":"663142f650b4130d190f78fe"
}
###
GET http://localhost:8080/api/nextwatches HTTP/1.1
Authorization: Bearer 
Content-Type: application/json

###
POST http://localhost:8080/api/nextwatches HTTP/1.1
Authorization: Bearer 
Content-Type: application/json

{
    "watch_id": "663142f650b4130d190f790c"
}

###
DELETE http://localhost:8080/api/nextwatches/663a13c829ee1a3c92a4bc8e HTTP/1.1
Authorization: Bearer
Content-Type: application/json

###
GET http://localhost:8080/api/nextwatches/6637a89e13d4accbc68d3013 HTTP/1.1
Authorization: Bearer 
Content-Type: application/json

###
GET http://localhost:8080/api/nextwatches/watch/663142f650b4130d190f78fe HTTP/1.1
Authorization: Bearer 
Content-Type: application/json

###
DELETE http://localhost:8080/api/nextwatches/6635ac71ac4c87c10043af09 HTTP/1.1
Authorization: Bearer 
Content-Type: application/json

###
GET http://localhost:8080/api/nextwatches/watch/663142f650b4130d190f78fe HTTP/1.1
Authorization: Bearer 
Content-Type: application/json

DELETE http://localhost:8080/api/nextwatches/6635ac71ac4c87c10043af09 HTTP/1.1
Authorization: Bearer 
Content-Type: application/json

###
GET http://localhost:8080/api/nextwatches/6637a89e13d4accbc68d3013 HTTP/1.1
Authorization: Bearer 
Content-Type: application/json


